### ISSUE TITLE
Audio segment bylines and reporter/producer pages

### ISSUE THREAD

**Issue by kookster** [PRX/theworld.org#102]
from Tania:
Hi guys, Just wanted to raise that this morning's reporters meeting focused entirely on why the current website does not have the capability to add reporter/producer bylines to audio segments. I am also getting questions from radio editors about this. I have not made them any promises and explained (many times) that the DACS exist for another purpose and that fixing it would take much time and many resources and needs to be fit within other tech team priorities. But I wanted to flag that we continue to get much pressure about this — and I agree with their sentiments as far as the importance of building this capability. As far as the new website, fixing this is 90% of people care about. It is their highest priority.

As far as why this is incredibly important:
- People want to get credit for their own work.
- Having those bylines reiterates that reporters/producers have a long track record of covering a particular topic, even when they haven't done a full digital story.
- Without bylines, audio-only stories go off into the ether and are hard to find on our website. People can't find their own work.

I expect many questions around all this next Friday. It would really reassure them if we come in with an intention/plan to address this with the new website.

**Comment by brandonhundt** [comment]
This is now in the API & accounted for in the Bio page design #103. Closing.
