### ISSUE TITLE
Update Campaign Monitor API key

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#111]
I think this is the only place we use the Campaign Monitor API. We need a new key, see below:

Hi there,
At CM Group, we are committed to keeping Campaign Monitor a safe and trusted application through our ongoing investment in security and reliability. To further protect your data, we recently took steps to strengthen the security of the Campaign Monitor API key format.
According to our records your account is using an old format key. We highly recommend you update your current API keys and take advantage of the improved security.
Find out how to update my API key
If you're running integrations or sending email using our API, this information is going to be most applicable to your IT and software teams, as well as anyone who manages third party integrations with Campaign Monitor (e.g. integrations with your content management system, CRM, or e-commerce site). So please forward this message to them. 
We appreciate you supporting this initiative in the best interests of the Campaign Monitor community. If you have any questions, please reach out to our customer support team.

**Comment by rpeterman-gp** [comment]
API key has been updated in Vercel prx-tech team secrets `cm-api-key`. Retrieve value from Campaign monitor dashboard and update your local `.env` file to submit newsletter subscriptions from local dev.
