### ISSUE TITLE
Vercel's edge cache is not being called.

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#144]
The Drupal API is now caching and that has helped performance. However, we are still getting timeouts loading some pages. Andrew and I noticed (okay Andrew noticed) that x-vercel-cache header is returning MISS. I'm suspecting if we can leverage the Vercel edge caching, we'd gain a lot of performance. 

Header values currently:
`x-vercel-cache: MISS` see: https://vercel.com/docs/edge-network/headers#x-vercel-cache
`cache-control: no-cache` see: https://vercel.com/docs/edge-network/headers#cache-control-header

**Comment by kookster** [comment]
Looks to me like there are cache settings for the homepage, but it doesn't seem to be working:
https://github.com/PRX/theworld.org/blob/master/vercel.json#L32-L36

**Comment by brandonhundt** [comment]
Also, noting that the floc block header isn't loading either.`"Permissions-Policy": "interest-cohort=()"`
