### ISSUE TITLE
Add redirect for old World in Words feed

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#239]
When Amplify accidentally soft launched the site, there is a feed redirect that was 404ing and causing a reported error in New Relic. We'll need the app to redirect `theworld.org/rss/twiw.xml` to `https://subtitlepod.com/feed/podcast`

**Comment by rpeterman-gp** [comment]
This has been implemented. Can be confirmed at https://beta.theworld.org/rss/twiw.xml.
