### ISSUE TITLE
Set up redirects

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#241]
It's likely wise to set up redirects captured in the Drupal settings doc on The world's frontend, just in case:

- `/rss/glohit.xml` > `http://feeds.feedburner.com/pri/global-hit`
- `/rss/geoquiz.xml` >`http://feeds.feedburner.com/pri/geo-quiz`
- `/rss/theworld.xml` > `http://feeds.feedburner.com/pri/theworld`
- `/collections*` > /`categories*` (example /collections/name redirects to /categories/name)
- `/sections*` > /`categories*`
- `/series*` > /`categories*`

**Comment by rpeterman-gp** [comment]
Issue moved to [PRX/Infrastructure #552](https://github.com/PRX/Infrastructure/issues/552) via [**ZenHub**](https://www.zenhub.com/)
