### ISSUE TITLE
Catch all redirect for theworld.org/rss* 

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#245]
I'm noticing that rss/science.xml is erroring out. And there are more of these rss links than original thought. Drupal knows how to handle these redirects, so lets get these redirected to the feeds subdomain.

 `theworld.org/rss/*` 301 redirected to `feeds.theworld.org/rss/*` as a catch all.

**Comment by rpeterman-gp** [comment]
These all don't directly to the feed URL, but get redirected in drupal to another. The example given in the ticket,`/rss/science.xml`, gets redirected to `/sections/science-tech-environment/feed`. I added a rule to handle this, much like the `/rss/tech.xml` rule. I also added the catch all rule, but be aware that it may not work as expected for all `/rss` prefixed paths.
