### ISSUE TITLE
Program page "Latest from our Partners" includes TW stories

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#246]
1. Go to theworld.org/programs/the-world
2. Scroll down to the story list in the sidebar "Latest from our Partners"
3. Note that there are TW stories in that list

Note: On the homepage this excludes stories from TW and the header is correct.

Options:
1. Change the header to be more inclusive
2. Exclude the program you are viewing from rendering in content.

I suspect the former is the easier option.

![The World _ The World from PRX _ Stories.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/94bea899-17bb-4921-91d2-12fd7a518617)

**Comment by rpeterman-gp** [comment]
Yes, the option 1 is the easiest. Just need to know what you want it to be.

**Comment by brandonhundt** [comment]
"Latest headlines"
