### ISSUE TITLE
Research: Search by Relevancy/Date

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#248]
Editors are requesting the ability to search by relevancy or date.

**Comment by rpeterman-gp** [comment]
The cse list API supports a sort parameter, but there will be a prerequisite to add structured data to the pages or sitemap that Google can interpret (https://developers.google.com/custom-search/docs/structured_data#using-meta-tags), followed by some time for Google to re-crawl our content to get that structured data. After that, the sort filter can be used to sort by broadcast/publish date, or any other property we want search to sort by.
