### ISSUE TITLE
Landing page header component

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#26]
- Banner image
- Logo
- Title
- Social links
- Podcast subscription button/modal

Used currently on Programs and Vertical pages.

See a category page for bare header component. https://www.pri.org/categories/global-nation-education
![Screen Shot 2019-10-24 at 2 57 43 PM](https://user-images.githubusercontent.com/369739/67520624-d0b6ff00-f66e-11e9-87de-704cb00fbb50.png)

**Comment by rpeterman-gp** [comment]
Completed with #105
