### ISSUE TITLE
CTAs: Program targeting doesn't appear to be working

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#291]
Thread: https://prx.slack.com/archives/C02K6JCMRRV/p1638897407268000

I'm trying to get it so the banner CTA only shows up on landing pages. 

1. In Drupal admin, edit a CTA (the world) and change the program targeting to "the World"
2. Note the API response is `"target_program": "3704"`
3. Go to theworld.org/programs/the-world note the banner doesn't appear

**Comment by rpeterman-gp** [comment]
Issue is in wrong repo. Moved to PublicRadioInternational/admin.theworld.org#1592
