### ISSUE TITLE
Homepage updating "freezes" when stories are added to the featured story list

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#292]
I just talked with the TW digital team. They explained an issue on the homepage they are experiencing... 

They said, if any stories are added to the featured stories list that the homepage stops updating. (at least the other featured story blocks that weren't curated stop updating. "Freeze" in their words)

And if they empty the featured story list, it resets but doesn't update.

However the stories below the CTA will update but not until the the featured story list is cleared out.

Slack Thread: https://prx.slack.com/archives/C02K6JCMRRV/p1638992170273100

**Comment by rpeterman-gp** [comment]
This issue was addressed with the change to SSR for all pages. Page content should now be updating as expected as caches expire.
