### ISSUE TITLE
Featured Categories menu

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#329]
Move the categories menu to the top of the homepage and list terms in line. We'll need to show the digital editors how to manage the terms, so they can add something about the Ukraine conflict, Cornavirus conversations, etc.

Examples:

CNN:
![CNN - Breaking News, Latest News and Videos](https://user-images.githubusercontent.com/369739/161333900-be84a93d-c1e5-44be-a4e7-a6c4981c5537.png)

NYT:
![The New York Times - Breaking News, US News, World News and Videos](https://user-images.githubusercontent.com/369739/161334086-ec600f5c-0a85-43e2-b447-b69d4e63c661.png)

**Comment by rpeterman-gp** [comment]
If we need a new menu in the CMS, we'll need a ticket for that in that repo.
