### ISSUE TITLE
Look into: Category description not showing up

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#346]
Haven't had the chance to look into this yet.

Anna Pratt says:
> it appears that on the public landing page for the Lumina immigration/education grant project, the description (The World, in collaboration with reporters from partner public radio stations, is developing enterprise reporting that intersects the immigrant experience with postsecondary education options for broadcast locally and nationally with support from Lumina.) doesn’t appear. but it does show up on the admin page (i put it in both the description field and body field on the admin page). i wonder how to make this visible on the public page? thanks for your help!

https://theworld.org/categories/course-0

**Comment by brandonhundt** [comment]
Description is there! Likely a caching issue.

**Comment by rpeterman-gp** [comment]
This seems to be working. The body content described is showing up in the sidebar now. May have been a cacheing delay.
