### ISSUE TITLE
Refactor Content body parsing for Guttenberg

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#351]
Migrated data should be okay, but as soon as they switch to Guttenberg, we need to be able to handle it

(Create and example post with ALL THE THINGS and style)

**Comment by brandonhundt** [comment]
@rpeterman-gp can this be closed now?

**Comment by rpeterman-gp** [comment]
@brandonhundt Yes. Any remaining styling can be handled in their own tickets. #434 did most of the work.
