### ISSUE TITLE
Add volume controls to persistent player

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#363]
Got at least one visitor comment about this. I think we can add them. Maybe even default to 80% volume too, so its not max?

Also, I might have suggested we could ignore them. But maybe not :)

**Comment by rpeterman-gp** [comment]
The default volume is already set to 80%. May want to go to something like 60%.

**Comment by rpeterman-gp** [comment]
Move this to a high since we received feedback of bad UX when user accidentally mutes player with keyboard shortcut.
