### ISSUE TITLE
Try performance mode?

### ISSUE THREAD

**Issue by kookster** [PRX/theworld.org#374]
https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html

Seems like this also then allows longer caching of requests on the server using `s-maxage`:
```
The s-maxage directive overrides max-age and lets you specify how long (in seconds) that you want content to remain at the CDN edge before it is refreshed from the origin server.
```

**Comment by brandonhundt** [comment]
Rick says this was turned on Monday. Closing, but may follow up after looking at performance.
