### ISSUE TITLE
Increase logging

### ISSUE THREAD

**Issue by kookster** [PRX/theworld.org#384]
It's hard with Amplify to know how much is being cached or executed, could we add more of our own logging to the SSR components to get more info?

**Comment by kookster** [comment]
Also check out NewRelic for instrumentation of client and server?

**Comment by kookster** [comment]
https://github.com/newrelic/newrelic-node-nextjs ?

**Comment by rpeterman-gp** [comment]
Got New Relic logging working for server logging, but once deployed to Amplify it doesn't work. Amplify deploy doesn't seem to run our defined `start` script, which is a known issue yet to be resolved (https://github.com/aws-amplify/amplify-hosting/issues/3115). Probably just have to do something similar to what we did in Play and add a custom error page that includes some request info in stdout before the thrown errors.
