### ISSUE TITLE
Long category name overflows width in landing page cards

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#441]
https://prx.slack.com/archives/CR59F3MU2/p1709934249253639

![StaticShot_08-03-2024_15-52-43](https://github.com/PRX/theworld.org/assets/369739/bf55986a-d784-4f0d-9a8c-53bed0a46da2)

The editors are going to shorten the name as a short-term fix, but we should probably fix the wrapping of the category name on landing pages.

**Comment by kookster** [comment]
(I think they should not use names this long, this is not a good use of categories or a fair expectation of the layout and resulting UX)
