### ISSUE TITLE
Long image credit layout

### ISSUE THREAD

**Issue by farski** [PRX/theworld.org#463]
Seen on iPhone

Long image credit seems to cause some layout issues

![IMG_5703](https://github.com/PRX/theworld.org/assets/3483/0b4ed872-c34f-40c4-bdec-f462d0271703)

**Comment by rpeterman-gp** [comment]
@farski Can you check and see if this issue still exists? I can't seem to reproduce it in MacOS Safari (don't have an iOS device). I think this may have been fixed by another ticket.

**Comment by farski** [comment]
That particular page displays correctly now. I don't know if there's a way to test it more generally.

**Comment by rpeterman-gp** [comment]
This was fixed with styling changes made with the improvements to vertical video embeds. Closing.
