### ISSUE TITLE
AudioPlayer component

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/theworld.org#47]
Player in Story and Episode layouts is pretty straight forward. 

Concerns:
- How are we going to resolve embed and popout URL's (currently handled with internal Drupal URL's)?
- How to not include app UI on embed and popout player pages?
- Should the styling be updated to fit theworld.org colors?
- Is it time to create a separate project for embeddable audio player, or utilize the PRX player?

**Comment by brandonhundt** [comment]
1. Maybe create a new story/episode route with only the player rendered?? But feel free to put the embeddable player in another ticket. 
2. Good question
3. Yes. Play button link blue. Background of the rest of the player can be the darker navy used in the header
4. Once TW is on Publish, we have the option of the PRX embeddable player.
