### ISSUE TITLE
Donately forms: How will these work?

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/theworld.org#54]
Right now we are just dropping a script tag into a page and the form renders. This how ever is not ideal for a SPA like the new TW frontend. Need to find a solutions that plays well with React and Next.js.

**Comment by brandonhundt** [comment]
Donately has their own frontend form page we can use. It might even be preferable to building out our own pages. Looking into.

**Comment by brandonhundt** [comment]
ResDev is switching to Classy on self hosted forms. Closing.
