### ISSUE TITLE
Redesign Menu

### ISSUE THREAD

**Issue by brandonhundt** [PRX/theworld.org#71]
I'm going to redesign the menu for the new frontend (and new frontend only). The accordion doesn't serve it very well. There are a lot fewer options now.

Maybe separate out the categories a bit (use the 5 pillar categories) below the header

**Comment by brandonhundt** [comment]
I've decided against the tag bar. 

Otherwise the menu changes are good to go.

**Comment by rpeterman-gp** [comment]
@brandonhundt The drawer changes should be its own ticket since that is an app wide component, not just the homepage.
