### ISSUE TITLE
Design for newsletter sign up page(s)

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/theworld.org#79]
While setting up the fields for the newsletter sign up content type (PublicRadioInternational/pri.org#1302
), I came to realize that a title and body field may not be enough to provide the content needed for an engaging newsletter signup page. Having a mock up of a newsletter page would help inform data requirements.

**Comment by brandonhundt** [comment]
This work was completed in Rick's buildout of the pages. Closing.
